name: Update IMD JSON (Bengaluru-safe)
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Fetch IMD (Bengaluru) and write imd.json
        env:
          IMD_SOURCE_URL: ${{ vars.IMD_SOURCE_URL || 'https://mausam.imd.gov.in/api/nowcast_district_api.php' }}
          IMD_DISTRICT_NAME: Bengaluru
          IMD_STATE_NAME: Karnataka
        run: |
          python scripts/fetch_imd_bengaluru.py
      - run: git config user.name "github-actions[bot]" && git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add imd.json
            git commit -m "update imd.json"
            git push
          else
            echo "No changes"
          fi
