name: Update IMD + OpenMeteo JSON

on:
  schedule:
    - cron: '0 * * * *'    # hourly (UTC) - change if you want less frequent
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps & fetch/run
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          python scripts/fetch_imd_combined.py

      - name: Commit imd.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add imd.json || true
            git commit -m "chore: update imd.json (automated) [skip ci]" || true
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
